- name: Supress Yum From Installing Multiple Kernel Copies.
  lineinfile:
    path: /etc/yum.conf
    regexp: ^installonly_limit=[0-9]+$
    line: installonly_limit=10
    state: present

- name: Disable HTTP Caching
  lineinfile:
    path: /etc/yum.conf
    regexp: ^ *?http_caching=.*$
    insertafter: ^\[main\]$
    line: http_caching=none
    state: present

- name: Disable Fastest Mirror Plugin 
  lineinfile:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: ^ *?enabled=.*$
    insertafter: ^\[main\]$
    line: enabled=0
    state: present

- name: Clean YUM Cache
  shell: yum clean all

