---
- name: Fix Networking Config
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no

  # Note(Dan): Variable prefix fn_ = fix networking.
  vars:

    # Note(Dan): XXX Fix Me! need to figure out a way to get consistent device
    #            names.
    fn_interfaces:
      # virtualbox: enp0s3
      virtualbox: eth0
      libvirt: eth0
      vmware: eth0

    fn_device_timeout: 600

    fn_interface: "{{fn_interfaces[provider|default('virtualbox')]}}"

  tasks:
    - name: Remove old ifcfg-<interface>.cfg
      file:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
        state: absent

    # Notes (Dan):
    #  UUID and HWADD may cause issues when virtual machine is moved around
    #  between providers so they are removed. Also configuration is greatly
    #  simplified.
    - name: Replace ifcfg-<interface>.cfg
      template:
        src: ifcfg-interface.j2
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
        mode: 0644

    # - name: Remove UUID
    #   lineinfile:
    #     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    #     regexp: ^#?\s*?UUID=".*?"$
    #     state: absent

    # - name: Remove Hardware MAC Address
    #   lineinfile:
    #     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    #     regexp: ^#? *?HWADDR=".*?"$
    #     state: absent

    # - name: Add Device
    #   lineinfile:
    #     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    #     regexp: ^#? *?DEVTIMEOUT=".*?"$
    #     line: "DEVTIMEOUT=\"{{fn_device_timeout}}\""
    #     state: present

    # - name: Add Device
    #   lineinfile:
    #     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    #     regexp: ^#? *?DEVICE=".*?"$
    #     line: "DEVICE=\"{{fn_interface}}\""
    #     state: present
