---
- name: Fix Networking Config
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no

  # Note(Dan): Variable prefix fn_ = fix networking.
  vars:

    # Note(Dan): XXX Fix Me! need to figure out a way to get consistent device
    #            names.
    fn_interfaces:
      virtualbox: enp0s3
      libvirt: eth0

    fn_interface: "{{fn_interfaces[provider|default('virtualbox')]}}"


  tasks:
    - name: Remove UUID
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
        regexp: ^#? *?UUID=".*?"$
        line: UseDNS no
        state: absent

    - name: Remove Hardware MAC Address
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
        regexp: ^#? *?HWADDR=".*?"$
        state: absent

    - name: Add Device
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
        regexp: ^#? *?DEVICE=".*?"$
        line: "DEVICE=\"{{fn_interface}}\""
        state: present
