---
- name: Install Whitney
  hosts: "{{hosts|d(host|d('all'))}}"
  # connection: paramiko
  gather_facts: no
  vars:
    fm_git_username: git
    fm_git_hostname: 15.252.78.7

    fm_download_base: /tmp
    fm_install_base: /opt
    fm_directory: Code---UI

    fm_ssl_country: US
    fm_ssl_state: Massachusetts
    fm_ssl_locality: Littleton
    fm_ssl_o: HPE
    fm_ssl_ou: DCIG
    fm_ssl_cn: whitney.local
    fm_ssl_email: daniel.l.wood@hpe.com
    fm_ssl_subject:
      - "C={{fm_ssl_country}}"
      - "ST={{fm_ssl_state}}"
      - "L={{fm_ssl_locality}}"
      - "O={{fm_ssl_o}}"
      - "OU={{fm_ssl_ou}}"
      - "CN={{fm_ssl_cn}}"
      - "emailAddress={{fm_ssl_email}}"
    fm_ssl_valid_days: 3560
    fm_ssl_key_type: rsa
    fm_ssl_key_size: 4096
    fm_ssl_key_file: server.key
    fm_ssl_crt_file: server.crt

    fm_autostart_name: whitney
    fm_yum_install_deps:
      - 'npm'
      - 'libicu'
      - 'libuv'
      - 'nodejs'

    fm_yum_build_deps: []

    fm_npm_install_deps:
      - '@angular/cli'
      - 'node-autostart'

  environment:
    http_proxy: "{{http_proxy|default(None)}}"

  tasks:
    - name: Install Required Dependencies
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{fm_yum_install_deps + fm_yum_build_deps}}"

    - name: Install Required NPM Dependencies
      npm:
        name: "{{item}}"
        global: true
        state: present
      with_items: "{{fm_npm_install_deps}}"

    # - name: Install Whitney Key File
    #   copy:
    #     src: ./id_packer.git
    #     dest: /tmp/id_packer.git
    #     mode: 0600

    # - name: Whitney Exists?
    #   stat:
    #     path: "{{fm_install_base}}/{{fm_directory}}"
    #   register: fm_stat

    # - name: Download Fusion
    #   git:
    #     ssh_opts: >-
    #       -o StrictHostKeyChecking=no
    #       -o UserKnownHostsFile=/dev/null
    #     repo: "{{fm_git_username}}@{{fm_git_hostname}}:/opt/git/whitney.git"
    #     clone: true
    #     key_file: /tmp/id_packer.git
    #     dest: "{{fm_download_base}}"
    #   when: not fm_stat.stat.exists

    - name: Download Whitney Install Files
      copy:
        src: ./whitney.tar.gz
        dest: "{{fm_download_base}}/whitney.tar.gz"
        remote_src: false
        # creates: "{{fm_download_base}}/whitney.tar.gz"

    - name: Unarchive Whitney Install Files
      unarchive:
        src: "{{fm_download_base}}/whitney.tar.gz"
        dest: "{{fm_download_base}}/"
        remote_src: true

    - name: Move Whitney Install Files
      command: "cp -r {{fm_download_base}}/Whitney/{{fm_directory}} {{fm_install_base}}/"
      args:
        creates: "{{fm_install_base}}/{{fm_directory}}/README.md"

    - name: Create SSL Directory - Whitney SSL
      file:
        path: "{{fm_install_base}}/{{fm_directory}}/ssl"
        state: directory

    - name: Create SSL Certificate - Whitney SSL
      command: >-
        openssl req
        -x509
        -nodes
        -newkey {{fm_ssl_key_type}}:{{fm_ssl_key_size}}
        -keyout {{fm_ssl_key_file}}
        -out {{fm_ssl_crt_file}}
        -days {{fm_ssl_valid_days}}
        -subj '/{{fm_ssl_subject|join('/')}}'
      args:
        chdir: "{{fm_install_base}}/{{fm_directory}}/ssl"
        creates: "{{fm_install_base}}/{{fm_directory}}/ssl/{{fm_ssl_key_file}}"

    - name: Set Whitney IP and SSL Cert
      lineinfile:
        path: "{{fm_install_base}}/{{fm_directory}}/package.json"
        regexp: "^( +)?\"start\": \"ng serve.*?\",$"
        line: "\\1\"start\": \"ng serve --host 0.0.0.0 --ssl 1 --ssl-key 'ssl/{{fm_ssl_key_file}}' --ssl-cert 'ssl/{{fm_ssl_crt_file}}'\","
        backrefs: true
        state: present

    - name: Install Whitney
      npm:
        path: "{{fm_install_base}}/{{fm_directory}}"
        state: present

    - name: Gather Facts Whitney - Autostart
      command: autostart check -n {{fm_autostart_name}}
      register: fm_as_facts
      changed_when: false

    - name: Set Facts Whitney - Autostart
      set_fact:
        fm_as_state: "{{(fm_as_facts.stdout_lines[1] == 'Autostart is enabled')|ternary(true,false)}}"

    - name: Enable Whitney - Autostart
      command: >-
        autostart enable
        -n '{{fm_autostart_name}}'
        -p '{{fm_install_base}}/{{fm_directory}}'
        -c 'npm start'
      when: fm_as_state == false

    - name: Remove Whitney Install Key File
      file:
        path: /tmp/id_packer.git
        state: absent

