---
- name: Install Local Repo
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
  vars:
    lr_name: local-repo
    lr_media: "{{media|default('remote')}}"

    lr_dev: /dev/sr0

  environment:
    http_proxy: "{{http_proxy|default(None)}}"
    https_proxy: "{{https_proxy|default(None)}}"

  pre_tasks:
    - name: Check CentOS local media is requested.
      meta: end_play
      when: lr_media != 'local'

  tasks:
    - name: Install CentOS Local Repository
      yum_repository:
        name: "{{lr_name}}"
        description: CentOS Local Repository
        baseurl: "file:///mnt/{{lr_name}}"
        gpgkey: "file:///mnt/{{lr_name}}/RPM-GPG-KEY-CentOS-7"
        enabled: false
        gpgcheck: true
        state: present

    - name: Create mount point folder.
      file:
        path: "/mnt/{{lr_name}}"
        state: directory

    - name: Mount | Mount CentOS Local CD
      command: "mount -t iso9660 {{lr_dev}} /mnt/{{lr_name}}"
