---
- name: Install Gnome Preferences
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    gp_base: /org/gnome/shell
    gp_key: enabled-extensions
    gp_extension_name_suffix: gnome-shell-extensions.gcampax.github.com
    gp_extension_package_prefix: gnome-shell-extension
    gp_extensions:
      - apps-menu
      - window-list
      - places-menu
      - alternate-tab
      - launch-new-instance
      - top-icons

  environment:
    http_proxy: "{{http_proxy|default(None)}}"

  tasks:
    # Install Gnome Extensions
    # ------------------------
    - name: Install Gnome Extensions
      yum:
        name: "{{gp_extension_package_prefix}}-{{item}}"
        state: present
      with_items: "{{gp_extensions}}"

    - name: Generate Gnome dconf Setting
      set_fact:
        gp_value: >-
          "[
          {%- for gp_extension in gp_extensions -%}
          '{{gp_extension}}@{{gp_extension_name_suffix}}'
          {%- if not loop.last -%},{%- endif -%}
          {%- endfor -%}
          ]"

    - name: Enable Gnome Extensions
      shell: |
        dbus-launch dconf write {{gp_base}}/{{gp_key}} {{gp_value}}
        dbus-launch dconf update
      become: true
      become_user: admin



    # Enable Automatic Login
    # ----------------------
    - name: Enable Gnome Automatic Login
      lineinfile:
        path: /etc/gdm/custom.conf
        # regexp: ^\[daemon\]$
        insertafter: ^\[daemon\]$
        line: |-
          AutomaticLoginEnable=True
          AutomaticLogin=admin
        state: present
