---
- name: Install Open VM Tools
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    vmware_target: "{{target|default('multi-user')}}"
    vmware_provider: "{{provider|default('')}}"
    vmware_media: "{{media|default('remote')}}"

    vmware_dependencies:
      multi-user:
        - open-vm-tools
      graphical:
        - open-vm-tools
        - open-vm-tools-desktop

  environment:
    http_proxy: "{{http_proxy|default(none)}}"
    https_proxy: "{{https_proxy|default(none)}}"

  pre_tasks:
    - name: Validate | Test if the provider is supported.
      meta: end_play
      when: vmware_provider != 'vmware'

    - name: Set | Set local repo
      set_fact:
        vmware_enable_repos: "local-repo"
        vmware_disable_repos: "*"
      when: vmware_media == "local"

    - name: Validate | Test connectivity to the system.
      ping:

    - name: Info | Gather facts on the system.
      setup:

  tasks:
    - name: Install | Install Dependencies.
      package:
        name: "{{item}}"
        enablerepo: "{{vmware_enable_repos|default(omit)}}"
        disablerepo: "{{vmware_disable_repos|default(omit)}}"
        state: present
      with_items: "{{vmware_dependencies[vmware_target]}}"

    - name: Enable | Start Open VM Tools
      service:
        name: vmtoolsd
        state: started
        enabled: yes
