---
- name: Install Browsers
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    gc_dependencies:
      - xdg-utils
      - wget
      - libXScrnSaver
      - redhat-lsb

  environment:
    http_proxy: "{{http_proxy|default(None)}}"

  tasks:
    - name: Install Google Chrome Dependencies
      yum:
        name: "{{item}}"
        state: latest
      with_items: "{{gc_dependencies}}"

    - name: Install Google Chrome Repository
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: "http://dl.google.com/linux/chrome/rpm/stable/$basearch"
        gpgkey: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        enabled: false
        gpgcheck: true
        state: present

    - name: Install Google Chrome
      yum:
        name: google-chrome-stable
        disablerepo: '*'
        enablerepo: google-chrome
        state: latest

    - name: Remove Google Chrome Repository
      yum_repository:
        name: google-chrome
        state: absent

    - name: Install Firefox
      yum:
        name: firefox
        state: latest
