---
- name: Install Gnome Preferences
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    # Gnome Extension Variables
    # -------------------------
    gp_base: org.gnome.shell
    gp_key: enabled-extensions
    gp_extension_name_suffix: gnome-shell-extensions.gcampax.github.com
    gp_extension_package_prefix: gnome-shell-extension
    gp_extensions:
      - apps-menu
      - window-list
      - places-menu
      - alternate-tab
      - launch-new-instance
      - top-icons


    # Gnome Desktop Variables
    # -----------------------
    gd_base: org.gnome.desktop

  environment:
    http_proxy: "{{http_proxy|default(None)}}"
    https_proxy: "{{https_proxy|default(None)}}"

  pre_tasks:
    - name: Validate | Test if the target is graphical.
      meta: end_play
      when: target|default('multi-user') != 'graphical'

  tasks:
    # Install Gnome Extensions
    # ------------------------
    - name: Install Gnome Extensions
      yum:
        name: "{{gp_extension_package_prefix}}-{{item}}"
        state: present
      with_items: "{{gp_extensions}}"

    - name: Generate Gnome dconf Setting
      set_fact:
        gp_value: >-
          "[
          {%- for gp_extension in gp_extensions -%}
          '{{gp_extension}}@{{gp_extension_name_suffix}}'
          {%- if not loop.last -%},{%- endif -%}
          {%- endfor -%}
          ]"

    - name: Enable Gnome Extensions
      shell: |
        dbus-launch gsettings set {{gp_base}} {{gp_key}} {{gp_value}}
      become: true
      become_user: admin


    # Disable Lock Screen 
    # -------------------
    - name: Disable Lock Screen
      shell: |
        dbus-launch gsettings set {{gd_base}}.lockdown disable-lock-screen false
      become: true
      become_user: admin


    # Disable Screen Saver Lock
    # -------------------------
    - name: Disable Screen Saver Lock
      shell: |
        dbus-launch gsettings set {{gd_base}}.screensaver lock-enabled false
      become: true
      become_user: admin


    # Disable Session Idle
    # --------------------
    - name: Disable Session Idle
      shell: |
        dbus-launch gsettings set {{gd_base}}.session idle-delay 0
      become: true
      become_user: admin


    # Disable Power Savings
    # --------------------
    - name: Disable Power Savings
      shell: |
        dbus-launch gsettings set org.gnome.settings-daemon.plugins.power active false
      become: true
      become_user: admin



    # Show Desktop Icons
    # ------------------
    - name: Enable Desktop Icons
      shell: |
        dbus-launch gsettings set {{gd_base}}.background show-desktop-icons true
      become: true
      become_user: admin


    # Show Clock Date
    # ---------------
    - name: Enable Clock Date
      shell: |
        dbus-launch gsettings set {{gd_base}}.interface clock-show-date true
      become: true
      become_user: admin


    # Enable Maximize, Minimize, and Close Buttons
    # --------------------------------------------
    - name: Enable Maximize, Minimize, and Close Buttons
      shell: |
        dbus-launch gsettings set {{gd_base}}.wm.preferences button-layout \"'appmenu:minimize,maximize,close'\"
      become: true
      become_user: admin


    # Enable Automatic Login
    # ----------------------
    - name: Enable Gnome Automatic Login
      lineinfile:
        path: /etc/gdm/custom.conf
        # regexp: ^\[daemon\]$
        insertafter: ^\[daemon\]$
        line: |-
          AutomaticLoginEnable=True
          AutomaticLogin=admin
        state: present
