---
- name: Install VirtualBox Guest Additions
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    version: "5.1.22"
    vbox_target: "{{target|default('multi-user')}}"
    vbox_provider: "{{provider|default('')}}"
    vbox_version: "{{version|default('latest')}}"
    vbox_media: "{{media|default('remote')}}"

    vbox_iso: "VBoxGuestAdditions_{{vbox_version}}.iso"
    vbox_base: "http://download.virtualbox.org/virtualbox/{{vbox_version}}"
    vbox_url: "{{vbox_base}}/{{vbox_iso}}"

    vbox_dependencies:
      - binutils
      - make
      - perl
      - bzip2
      - gcc
      - cpp
      - "kernel-devel-{{kernel_version}}"
      - "kernel-headers-{{kernel_version}}"
      - glibc-devel
      - glibc-headers
      - libmpc
      - mpfr

    vbox_nox11: ''

  environment:
    http_proxy: "{{http_proxy|default(none)}}"
    https_proxy: "{{https_proxy|default(none)}}"

  pre_tasks:
    - name: Validate | Test if the provider is supported.
      meta: end_play
      when: vbox_provider != 'virtualbox'

    - name: Validate | Test if the target is graphical.
      set_fact:
        vbox_nox11: '--nox11'
      when: vbox_target != 'graphical'

    - name: Set | Set local repo
      set_fact:
        vbox_enable_repos: "local-repo"
        vbox_disable_repos: "*"
      when: vbox_media == "local"

    - name: Validate | Test connectivity to the system.
      ping:

    - name: Info | Gather facts on the system.
      setup:

  tasks:
    - name: Get | Kernel Version Data
      command: uname -r
      changed_when: false
      register: kernel_version_output

    - name: Set | Kernel Version Data
      set_fact:
        kernel_version: "{{kernel_version_output.stdout}}"

    - name: Install | Install Dependencies.
      package:
        name: "{{item}}"
        enablerepo: "{{vbox_enable_repos|default(omit)}}"
        disablerepo: "{{vbox_disable_repos|default(omit)}}"
        state: present
      with_items: "{{vbox_dependencies}}"

    - name: Verify VBoxGuestAdditions.iso exists.
      stat:
        path: "/tmp/{{vbox_iso}}"
      register: vbox_stat

    - name: Get | Download VirtualBox guest additions ISO to the system.
      get_url:
        url: "{{vbox_url}}"
        dest: "/tmp"
      when: not vbox_stat.stat.exists

    - name: Mount | Mount VirtualBox guest additions ISO.
      mount:
        path: /tmp/vbox
        src: "/tmp/{{vbox_iso}}"
        opts: loop
        fstype: iso9660
        state: mounted

    - name: Install | Install VirtualBox guest additions ISO.
      command: "./VBoxLinuxAdditions.run {{vbox_nox11}}"
      args:
        chdir: /tmp/vbox

    - name: Unmount | Unmount VirtualBox guest additions ISO.
      mount:
        path: /tmp/vbox
        state: absent

    - name: Delete | Delete VirtualBox ISO from the system.
      file:
        path: "/tmp/{{vbox_iso}}"
        state: absent

    - name: Clean VirtualBox guest additions Install Dependencies
      package:
        name: "{{item}}"
        state: present
      with_items: "{{vbox_dependencies}}"

  post_tasks:
    # Note(Dan): This fixes issues with the guest additions video driver not
    #            working until after two of reboots.
    - name: Fix | Reboot the system twice.
      include: pb_reboot_server.yaml
      with_items:
        - 1
        - 2
