---
- name: Optimize Disk Size
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no

  vars:
    zero_partitions:
      - /
      - /boot/

  tasks:
    - name: Clean YUM Cache
      shell: yum clean all
      
    - name: Remove Log Files
      shell: find /var/log/ -name *.log -exec rm -f {} \;

    - name: Zero Free Space
      shell: |
        count=$(expr $(df --sync -kP {{item}} | tail -n1 | awk -F ' ' '{print $4}') - 1)
        dd if=/dev/zero of={{item}}whitespace bs=1M count=$count
        rm {{item}}whitespace
      with_items: "{{zero_partitions}}"
