---
- name: Optimize Yum Config
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no

  tasks:
    - name: Supress Yum From Installing Multiple Kernel Copies.
      lineinfile:
        path: /etc/yum.conf
        regexp: ^installonly_limit=[0-9]+$
        line: installonly_limit=10
        state: present

    # Note (Dan): The regexp parameter is not needed unless you are worried that
    #             the line already exists in the line file.
    - name: Fix - Disable HTTP Caching
      lineinfile:
        path: /etc/yum.conf
        regexp: ^ *?http_caching=.*$
        insertafter: ^\[main\]$
        line: http_caching=none
        state: present

    # Note (Dan): The regexp parameter is not needed unless you are worried that
    #             the line already exists in the line file.
    - name: Fix - Disable Fastest Mirror Plugin 
      lineinfile:
        path: /etc/yum/pluginconf.d/fastestmirror.conf
        regexp: ^ *?enabled=.*$
        insertafter: ^\[main\]$
        line: enabled=0
        state: present

    - name: Fix - Clean YUM Cache
      shell: yum clean all
      
