---
- name: Bootstrap System For Use With Ansible 
  hosts: all
  gather_facts: no
 
  vars:

  pre_tasks:
    # - name: "Create | Deploy User "
    #     user:
    #       name: "{{bs_deploy_user}}"
    #       comment: "{{bs_deploy_user}}"
    #       group: "{{bs_deploy_user}}"
    #       groups: "{{deploy_user_sudo_group}}"
    #       shell: /bin/bash
    #       skeleton: /etc/skel
    #       update_password: always
    #       uid: 970
    #     become: true

    # Initialize - /etc/sudoers.d/admin
    # -----------------------------------
    - name: Install | Admin user sudo overrides.
      copy:
        src: "admin.sudoers"
        dest: "/etc/sudoers.d/admin"
        mode: 0400
      become: true
