- name: Remove old ifcfg-<interface>.cfg
  file:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    state: absent

# Notes (Dan):
#  UUID and HWADD may cause issues when virtual machine is moved around
#  between providers so they are removed. Also configuration is greatly
#  simplified.
- name: Replace ifcfg-<interface>.cfg
  template:
    src: ./templates/ifcfg-interface.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
    mode: 0644

# Note(Dan): OLD Stuff Below. I mostly keep it around for reference, but I
#            should delete it. ;)

# - name: Remove UUID
#   lineinfile:
#     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
#     regexp: ^#?\s*?UUID=".*?"$
#     state: absent

# - name: Remove Hardware MAC Address
#   lineinfile:
#     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
#     regexp: ^#? *?HWADDR=".*?"$
#     state: absent

# - name: Add Device
#   lineinfile:
#     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
#     regexp: ^#? *?DEVTIMEOUT=".*?"$
#     line: "DEVTIMEOUT=\"{{fn_device_timeout}}\""
#     state: present

# - name: Add Device
#   lineinfile:
#     path: "/etc/sysconfig/network-scripts/ifcfg-{{fn_interface}}"
#     regexp: ^#? *?DEVICE=".*?"$
#     line: "DEVICE=\"{{fn_interface}}\""
#     state: present
