---
- name: Install Browsers
  hosts: "{{hosts|d(host|d('all'))}}"
  gather_facts: no
 
  vars:
    gc_dependencies:
      - xdg-utils
      - wget
      - libXScrnSaver
      - redhat-lsb

    gc_selenium_dependencies:
      - unzip

    gc_selenium_version: 2.29
    gc_selenium_base: http://chromedriver.storage.googleapis.com
    gc_selenium_file: chromedriver_linux64.zip

    ff_selenium_dependencies:
      - libcanberra-gtk2 
      - xorg-x11-server-Xvfb

    ff_selenium_base: ~/.mozilla/firefox
    ff_selenium_file: selenium

  environment:
    http_proxy: "{{http_proxy|default(None)}}"
    https_proxy: "{{https_proxy|default(None)}}"

  pre_tasks:
    - name: Validate | Test if the target is graphical.
      meta: end_play
      when: target|default('multi-user') != 'graphical'

  tasks:
    # Install Google Chrome
    # ---------------------
    - name: Install Google Chrome Dependencies
      yum:
        name: "{{item}}"
        state: latest
      with_items: "{{gc_dependencies}}"

    - name: Install Google Chrome Repository
      yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: "http://dl.google.com/linux/chrome/rpm/stable/$basearch"
        gpgkey: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        enabled: false
        gpgcheck: true
        state: present

    - name: Install Google Chrome
      yum:
        name: google-chrome-stable
        disablerepo: '*'
        enablerepo: google-chrome
        state: latest

    - name: Remove Google Chrome Repository
      yum_repository:
        name: google-chrome
        state: absent

    - name: Adjust Google Chrome Repository Cron
      replace:
        path: "/etc/cron.daily/google-chrome"
        regexp: ^(?:#| +)?enabled=(?:0|1)$
        replace: "enabled=0"

    - name: Install Google Chrome Selenium Dependencies
      yum:
        name: "{{item}}"
        state: latest
      with_items: "{{gc_selenium_dependencies}}"

    - name: Download Google Chrome Selenium Driver
      get_url:
        url: "{{gc_selenium_base}}/{{gc_selenium_version}}/{{gc_selenium_file}}"
        dest: "/tmp/{{gc_selenium_file}}"
        validate_certs: no

    - name: Extract Google Chrome Selenium Driver
      unarchive:
        src: "/tmp/{{gc_selenium_file}}"
        dest: "/tmp"
        remote_src: true
        creates: /tmp/chromedriver

    - name: Install Google Chrome Selenium Driver
      copy:
        src: /tmp/chromedriver
        dest: /usr/local/bin/chromedriver
        mode: 0755
        remote_src: true

    # Install Firefox
    # ---------------
    - name: Install Firefox Selenium Dependencies
      yum:
        name: "{{item}}"
        state: latest
      with_items: "{{ff_selenium_dependencies}}"

    - name: Install Firefox
      yum:
        name: firefox
        state: latest

    - name: Create Firefox Profile
      shell: |
        xvfb-run firefox -CreateProfile {{ff_selenium_file}}
        mv {{ff_selenium_base}}/*.{{ff_selenium_file}} {{ff_selenium_base}}/{{ff_selenium_file}}
        rm {{ff_selenium_base}}/profiles.ini
      become: true
      become_user: admin
