hostname: "{{name|default('localhost')}}.local"

profiles:
  admin:
    name: admin
    group: admin
    uid: 1000
    gid: 1000
    comment: Administrator
    password: password
    admin: true
    vagrant: true

  # support:
  #   name: support
  #   group: support
  #   uid: 1001
  #   gid: 1001
  #   comment: Support
  #   password: password
  #   admin: true

  vagrant:
    name: vagrant
    group: vagrant
    uid: 1002
    gid: 1002
    comment: Vagrant
    password: vagrant
    vagrant: true
    hidden: true

