
Vagrant.configure("2") do |config|
  config.ssh.username = "admin"
  config.ssh.password = "password"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096 
    libvirt.cpus = 4

    libvirt.graphics_type = "spice"
    libvirt.graphics_autoport = "yes"
    libvirt.video_type = "qxl"

    libvirt.channel :type => "spicevmc",
                    :target_name => "com.redhat.spice.0",
                    :target_type => "virtio"

    libvirt.channel :type => "unix",
                    :target_name => "org.qemu.guest_agent.0",
                    :target_type => "virtio"
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
